# -*- coding: utf-8 -*-
"""Calcu.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HvDJcb8WjxSfc7I3gFuHW0FafFpsX3h5
"""

input1=int(input("Enter the value 1= "))
input2=int(input("Enter the value 2= "))
Sign=input("Enter operator: ")

def calculator(value1,value2,operator):
  if operator=="+":
    return value1+value2
  elif operator=="-":
    return value1-value2
  elif operator=="/":
    return value1/value2
  else:
    return print("invalid operation")

result=calculator(input1,input2,Sign)
print(result)