# -*- coding: utf-8 -*-
"""Calcu1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HvDJcb8WjxSfc7I3gFuHW0FafFpsX3h5
"""

# Create a calculator function
# The function should accept three parameters:
# first_number: a numeric value for the math operation
# second_number: a numeric value for the math operation
# operation: the word 'add' or 'subtract'
# the function should return the result of the two numbers added or subtracted
# based on the value passed in for the operator
#
# Test your function with the values 6,4, add 
# Should return 10
#
# Test your function with the values 6,4, subtract 
# Should return 2
# 
# BONUS: Test your function with the values 6, 4 and divide 
# Have your function return an error message when invalid values are received




input1=int(input("Enter the value 1= "))      #taking input from the user in this case take 6 
input2=int(input("Enter the value 2= "))      #taking input from user in this case take 4
Sign=input("Enter operator: ")

def calculator(value1,value2,operator):       #defining the function and passing all three parameters as mentioned above
  if operator=="+":
    return value1+value2
  elif operator=="-":
    return value1-value2
  elif operator=="/":
    return value1/value2
  else:
    return print("invalid operation")

result=calculator(input1,input2,Sign)       #calling the calculator function and storing the value in result
print(result)                               #printing the result